### ISSUE TITLE
Make Dockerfile and build instructions for Docker build container

### ISSUE THREAD

**Issue by ErixenCruz** [CesiumGS/cdb-to-3dtiles#13]
Requirements so far: 
- gdal v3.0.4
- OpenSceneGraph v3.4.0
- libpng
- libjpeg
- zlib

@lilleyse @baothientran If there is anything else let's put it down here

**Comment by lilleyse** [comment]
This issue can be closed since we have a working `Dockerfile`, but I opened https://github.com/CesiumGS/cdb-to-3dtiles/issues/30 to address some portability issues with the binaries.
