### ISSUE TITLE
Provide utility to let client combine multiple converted tilesets together

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cdb-to-3dtiles#19]
Currently each dataset is converted into a separate tileset. We should provide a utility to let client combine them together into a single global tileset

**Comment by lilleyse** [comment]
I think it's worthwhile to add this functionality to the converter by default.

There should be a top-level tileset.json (e.g. SanDiego/tileset.json) and a tileset.json for each geocell (e.g. Tiles/N32/W118/tileset.json). The top-level tileset.json should point to all the geocell tilesets, and each geocell tileset should point to the layer tilesets.

This, in conjunction with https://github.com/CesiumGS/cdb-to-3dtiles/issues/27, will be a nice improvement for the 3D Tiles output.
