### ISSUE TITLE
Set geometric error to be 0 for leaf tile

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cdb-to-3dtiles#21]

**Comment by nithinp7** [comment]
It looks likes the same problem exists in the hard-coded 3D Tiles json files that are compared against the generated 3D Tiles during testing. For example, this one has several leaf tiles with non-zero geometric error: 
https://github.com/CesiumGS/cdb-to-3dtiles/blob/master/Tests/Data/ElevationMoreLODPositiveImagery/VerifiedTileset.json

So while fixing this bug, these verification json files also need to be refactored so the leaf tiles are being properly tested for a geometric error of 0.
