### ISSUE TITLE
Elevation layer and imagery layer should have the same LOD

### ISSUE THREAD

**Issue by baothientran** [CesiumGS/cdb-to-3dtiles#4]
Elevation layer and imagery layer can have different LOD in CDB. However, when converting to tile, they should have the same LOD since imagery is used as texture for elevation

**Comment by GamingDad29** [comment]
Hey, we have ran the cdb-to-3dtile converter on a large cdb database where the elevation has I think, 3 LOD's and the Imagery has around 9 LOD's that were produced when generating the CDB using Presagis Terra Vista. When we converted this CDB to 3DTiles and view it in our IG, we are seeing a major drop-off in imagery resolution. Our source data was DTED and JP2 files. I know in the converter tool, there is an option to take the elevation LOD , but if that's not specified when running the tool, that wouldn't apply to the conversion right? Is there a different LOD call out I can do that would ensure it gets the highest LOD applied to the conversion, even if it slows performance of the IG we intend to view the tiles in? All assistance is greatly appreciated as we are pretty new to producing 3dTiles.
