### ISSUE TITLE
[root@localhost cdb-to-3dtiles]# cmake --build Build --config Release -j 4

### ISSUE THREAD

**Issue by gisspace** [CesiumGS/cdb-to-3dtiles#49]
../CDBTo3DTiles/libCDBTo3DTiles.a(CDBTo3DTiles.cpp.o):CDBTo3DTiles.cpp:(.text._ZNSt6vectorINSt10filesystem7__cxx114pathESaIS2_EE17_M_realloc_insertIJRS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_[_ZNSt6vectorINSt10filesystem7__cxx114pathESaIS2_EE17_M_realloc_insertIJRS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_]+0x254): more undefined references to `std::filesystem::__cxx11::path::_M_split_cmpts()' follow
//usr/local/lib/libproj.so.19: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()@GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
gmake[2]: *** [Tests/CMakeFiles/Tests.dir/build.make:262: Tests/Tests] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2600: Tests/CMakeFiles/Tests.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2

**Comment by sanjeetsuhag** [comment]
@gisspace Based on #50, it seems like you are using GCC 10, whereas we have only tested it with GCC 9. Could you please try building with GCC 9 and confirm if the issues you are experiencing still persist?

**Comment by gisspace** [comment]
thanks，I will try to compile on GCC 9
