### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gisspace** [CesiumGS/cdb-to-3dtiles#50]
Centos8.3 
gcc/g++ 10.1.0
[root@localhost CDB]# ./CDBConverter -h
Convert CDB to 3D Tiles
Usage:
  CDBConverter [OPTION...]

  -i, --input arg               CDB directory
  -o, --output arg              3D Tiles output directory
      --combine arg             Combine converted datasets into one tileset.
                                Each dataset format is
                                {DatasetName}_{ComponentSelector1}_{ComponentSelector2}. Repeat this
                                option to group different dataset into
                                different tilesets. E.g:
                                --combine=Elevation_1_1,GSModels_1_1 --combine=GTModels_2_1,GTModels_1_1
                                will combine Elevation_1_1 and GSModels_1_1
                                into one tileset. GTModels_2_1 and GTModels_1_1
                                will be combined into a different tileset
                                (default:
                                Elevation_1_1,GSModels_1_1,GTModels_2_1,GTModels_1_1)
      --elevation-normal        Generate elevation normal
      --elevation-lod           Generate elevation and imagery based on
                                elevation LOD only
      --elevation-decimate-error arg
                                Set target error when decimating elevation
                                mesh. Target error is normalized to 0..1 (0.01
                                means the simplifier maintains the error to be
                                below 1% of the mesh extents) (default: 0.01)
      --elevation-threshold-indices arg
                                Set target percent of indices when decimating
                                elevation mesh (default: 0.3)
  -h, --help                    Print usage

Segmentation fault (core dumped)

**Comment by yoavMalca** [comment]
This issue happend to me either can you please explain what did you changed in the environment?
